<?php

namespace App\Models\Lists;

use App\Models\AbstractIblockPropertyValuesTable;
use App\Models\Lists\ProceduresPropertyValuesTable;
use Bitrix\Main\Entity\ReferenceField;


class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    protected static string $apiCode = 'Doctors';

    /*public static function getMap(): array
    {
        $map = [
            'PROCEDURES_L' => new ReferenceField(
                'PROCEDURES_L',
                ProceduresPropertyValuesTable::class,
                ['=this.PROCEDURES' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];


        return parent::getMap() + $map; // TODO: Change the autogenerated stub
    }*/


}